### ISSUE TITLE
I don't understand how to use this, or how it works

### ISSUE THREAD

**Issue by lazarillo** [frostming/pdm-vscode#7]
Sorry, this is not an issue with the code, but with how to use it.

I understand that this adds the analysis and autocomplete paths:

```json
    "python.analysis.extraPaths": [
        "${workspaceFolder}/__pypackages__/3.8/lib"
    ],
    "python.autoComplete.extraPaths": [
        "${workspaceFolder}/__pypackages__/3.8/lib"
    ],
```

But because I am a hardcore supporter of the PEP that removes virtual environments (582??),  _normally_ I run `pdm run python -m <my_module>`.  Or, more generally, I always start with `pdm...` to make sure the environment is correct.  I understand that this _primarily_ ensures that the `__pypackages__` folder is added to the `$PATH` variable, but doesn't it do more than this?  Eg, doesn't the `pdm` command also ensure that the right version of Python is being used?  I don't understand how this is being done with this add-on.

-----

In other words, don't I also need a new _debugger type_, so that I can have a `launch.json` file that looks something like this?

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "PDM: Current File",
            "type": "pdm",
            "request": "launch",
            "program": "run python ${file}",
            "console": "integratedTerminal",
            "cwd": "${workspaceFolder}/data/fake",
            "justMyCode": true
        },
    ]
}
```

Note explicitly:  I have changed the `type` to `pdm` and I have changed the `program` to say `run python ${file}`.

If I don't need that, and I can just use a "normal" launch config that has `type` set to `python` and `program` set to `${file}`, can you explain how/why that works?

I spent a lot of time trying to get this extension to work, and I eventually figured out that the `analysis` path was wrong because the `__pypackages__` was not directly under the top level (it's a big mono-repo).  Once I fixed that, though, I realized I really didn't understand why/how it worked.

**Comment by frostming** [comment]
> Or, more generally, I always start with `pdm...` to make sure the environment is correct. I understand that this _primarily_ ensures that the `__pypackages__` folder is added to the `$PATH` variable

Not `$PATH`, it is used for the language server to discover extra paths to provide code hints and reference jumping.



> If I don't need that, and I can just use a "normal" launch config that has `type` set to `python` and `program` set to `${file}`, can you explain how/why that works?

In hard PEP 582 mode, the paths will be seen by the interpreter due to [it enabled globally](https://pdm.fming.dev/latest/usage/pep582/#enable-pep-582-globally). The debugger is a normal interpreter, so it is aware of the `__pypackages__`.

After all, since PEP 582 is rejected, this project isn't considered needed any more. If you don't understand just stop using it.
We are not responsible for answering such rude questions.

**Comment by lazarillo** [comment]
OK, I'll stop using that feature.  I really like PDM and I don't see anything that I wrote which would have come off as rude.  Thanks for your hard work in making a great tool.  I think PDM is a great contributor to cleaning up the mess which is Python packages.
